runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /adminz(/.*)?
  script: admin.app
  secure: always
  login: admin

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest

skip_files:
- asset_sources/
- .git/
